# Generated by Django 5.2.1 on 2025-05-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movieinfo_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
