# Generated by Django 5.2.1 on 2025-05-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movieinfo_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='year',
            field=models.IntegerField(),
        ),
    ]
