# Generated by Django 5.2.1 on 2025-05-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movieinfo_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieinfo',
            old_name='summary',
            new_name='desc',
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
