# Generated by Django 5.2.1 on 2025-05-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_rename_summary_movieinfo_desc_alter_movieinfo_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='desc',
            field=models.TextField(),
        ),
    ]
