# Generated by Django 5.2.1 on 2025-05-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_directors_alter_movieinfo_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='poster',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
