# Generated by Django 5.2.1 on 2025-05-24 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_movieinfo_directed_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieinfo',
            old_name='Directed_by',
            new_name='directed_by',
        ),
    ]
