# Generated by Django 5.2.1 on 2025-05-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_rename_directed_by_movieinfo_directed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='actors',
            field=models.ManyToManyField(related_name='movie_actors', to='movies.actors'),
        ),
    ]
